### ISSUE TITLE
`cargo install cargo-crev` fails.

### ISSUE THREAD

**Issue by vi** [crev-dev/cargo-crev#369]
```
   Compiling crev-data v0.17.0
error[E0599]: no function or associated item named `from_bytes` found for struct `ed25519_dalek::Signature` in the current scope
  --> /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/crev-data-0.17.0/src/id.rs:80:59
   |
80 |                 let signature = ed25519_dalek::Signature::from_bytes(&sig_bytes)?;
   |                                                           ^^^^^^^^^^
   |                                                           |
   |                                                           function or associated item not found in `ed25519_dalek::Signature`
   |                                                           help: there is an associated function with a similar name: `to_bytes`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use ed25519_dalek::ed25519::signature::Signature;`

error[E0599]: no method named `verify` found for struct `ed25519_dalek::PublicKey` in the current scope
  --> /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/crev-data-0.17.0/src/id.rs:81:24
   |
81 |                 pubkey.verify(&content, &signature)?;
   |                        ^^^^^^ method not found in `ed25519_dalek::PublicKey`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use ed25519_dalek::Verifier;`

error[E0599]: no method named `sign` found for struct `ed25519_dalek::Keypair` in the current scope
   --> /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/crev-data-0.17.0/src/id.rs:198:22
    |
198 |         self.keypair.sign(msg).to_bytes().to_vec()
    |                      ^^^^ method not found in `ed25519_dalek::Keypair`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use ed25519_dalek::Signer;`

error: aborting due to 3 previous errors
```

**Comment by dpc** [comment]
Caused by #368 . Install git version please. :)

**Comment by vi** [comment]
Thanks, already done it.

**Comment by rnestler** [comment]
I hit this issue as well.

> Caused by #368 . Install git version please. :)

Maybe it would make sense to publish a bug fix release and yank the broken version?

**Comment by dpc** [comment]
I think this is no longer a problem.
